language: node_js

sudo: false

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

install:
  - node -v
  - which node
  - clang++ -v
  - which clang++
  - make ${BUILDTYPE}

# *Here we run tests*
# We prefer running tests in the 'before_script' section rather than 'script' to ensure fast failure.
# Be aware that if you use the 'script' section it will continue running all commands in the section even if one line fails.
# This is documented at https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build
# We don't want this behavior because otherwise we might risk publishing builds when the tests did not pass.
# For this reason, we disable the 'script' section below, since we prefer using 'before_script'.
before_script:
  - npm test

script:
  # after successful tests, publish binaries if specified in commit message
  - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")

# the matrix allows you to specify different operating systems and environments to
# run your tests and build binaries
matrix:
  include:

    ## ** Builds that are published **

    # linux cfi build node v10/release
    - os: linux
      env: BUILDTYPE=release TOOLSET=cfi CXXFLAGS="-fsanitize=cfi -fsanitize-blacklist=$PWD/blacklist.txt -fvisibility=hidden" LDFLAGS="-fsanitize=cfi"
      node_js: 10
    # linux publishable node v12/release
    - os: linux
      env: BUILDTYPE=release
      node_js: 12
    # linux publishable node v10/release
    - os: linux
      env: BUILDTYPE=release
      node_js: 10
    # linux publishable node v10/debug
    - os: linux
      env: BUILDTYPE=debug
      node_js: 10
    # linux publishable node v12/release
    - os: linux
      env: BUILDTYPE=release
      node_js: 12
    # linux publishable node v12/debug
    - os: linux
      env: BUILDTYPE=debug
      node_js: 12
    # linux publishable node v13/release
    - os: linux
      env: BUILDTYPE=release
      node_js: 13
    # linux publishable node v13/debug
    - os: linux
      env: BUILDTYPE=debug
      node_js: 13
    # osx publishable node v10/release
    - os: osx
      osx_image: xcode11
      env: BUILDTYPE=release
      node_js: 10
    # osx publishable node v12/release
    - os: osx
      osx_image: xcode11
      env: BUILDTYPE=release
      node_js: 12
    # linux sanitizer build node v10/debug
    - os: linux
      env: BUILDTYPE=debug TOOLSET=asan
      node_js: 10
      sudo: required
      # Overrides `install` to set up custom asan flags
      install:
        - make sanitize
      # Overrides `before_script` (tests are already run in `make sanitize`)
      before_script:
        - true
    # osx sanitizer build node v10/debug
    - os: osx
      osx_image: xcode11
      env: BUILDTYPE=debug TOOLSET=asan
      node_js: 10
      sudo: required
      # Overrides `install` to set up custom asan flags
      install:
        - make sanitize
      # Overrides `before_script` (tests are already run in `make sanitize`)
      before_script:
        - true
    ## ** Builds that do not get published **

    # g++ build (default builds all use clang++)
    - os: linux
      env: BUILDTYPE=debug CXX="g++-6" CC="gcc-6" LINK="g++-6" AR="ar" NM="nm"
      node_js: 10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-6-dev
            - g++-6
      # Overrides `install` to avoid initializing clang toolchain
      install:
        - make ${BUILDTYPE}
      # Overrides `script` to disable publishing
      script:
        - true
    # Coverage build
    - os: linux
      env: BUILDTYPE=debug CXXFLAGS="--coverage" LDFLAGS="--coverage"
      node_js: 10
      # Overrides `script` to publish coverage data to codecov
      script:
        - export PATH=$(pwd)/mason_packages/.link/bin/:${PATH}
        - which llvm-cov
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        # Workaround until we can avoid problem after https://github.com/travis-ci/travis-build/pull/1263 lands
        - PATH=$(echo "$PATH" | sed 's/.\/node_modules\/.bin://')
        - ./codecov -x "llvm-cov gcov" -Z
    # Clang format build
    - os: linux
      # can be generic since we don't need nodejs to run formatting
      language: generic
      env: CLANG_FORMAT
      # Overrides `install` to avoid initializing clang toolchain
      install:
        # Run the clang-format script. Any code formatting changes
        # will trigger the build to fail (idea here is to get us to pay attention
        # and get in the habit of running these locally before committing)
        - make format
      # Overrides `before_script`, no need to run tests
      before_script:
        - true
      # Overrides `script` to disable publishing
      script:
        - true
    # Clang tidy build
    - os: linux
      env: CLANG_TIDY
      node_js: 10
      # Overrides `install` to avoid initializing clang toolchain
      install:
        # First run the clang-tidy target
        # Any code formatting fixes automatically applied by clang-tidy
        # will trigger the build to fail (idea here is to get us to pay attention
        # and get in the habit of running these locally before committing)
        - make tidy
      # Overrides `before_script`, no need to run tests
      before_script:
        - true
      # Overrides `script` to disable publishing
      script:
        - true
